typography_spectrum: 0.7867449701298028
color:
  saturation: 0.6228247273247689
  brandStrength: 0.9776686618570238
  lightness: 0.4709113040007651
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.5379774472676218
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.09394088410772383
analytics:
  twitter: null
  google: UA-78956265-1
  facebook: null
name: travels w// betty
cta:
  bucket: null
  version: null
  domain: null
style: the-composer
navigation:
  - name: b l o g
    id: 2c4f8b91-f250-4d97-b48c-ec7e58b9313b
    type: content
  - name: i n s t a
    url: 'https://www.instagram.com/that_betty/'
    type: external
  - name: linkedIN
    id: e705be94-fa07-4c50-ac86-e928d07edf92
    type: content
  - name: U P D A T E S
    url: 'http://www.123contactform.com/form-2104949/My-Form'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: h o m e
description: b e t t y
purpose: []
