layout_spectrum: 0.448961173763388
typography_spectrum: 0.5420253796563806
color:
  saturation: 0.26325469228688003
  brandStrength: 0.5476234167012949
  lightness: 0.6293802076160429
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  rhythmicContrast: 0.9086222785976854
coverPrefs:
  filter: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-78956265-1
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c253c39c-783b-47f9-b9a1-9ea3d95b7d07.jpg
name: travels with betty
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: i g
    url: 'https://www.instagram.com/that_betty/'
    type: external
  - name: signup
    url: 'http://www.123contactform.com/form-2104949/My-Form'
    type: external
  - name: SHOP
    url: 'http://thegrid.ai/ursa/'
    type: external
  - name: b l o g
    id: 2c4f8b91-f250-4d97-b48c-ec7e58b9313b
    type: content
  - name: gallery
    url: 'http://thegrid.ai/snuggler/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
content: []
description: ''
purpose:
  - type: internal
    label: blog!
    item: 2c4f8b91-f250-4d97-b48c-ec7e58b9313b
  - type: external
    url: 'http://thegrid.ai/ursa/'
    label: Shop
