typography_spectrum: 0.4785993106197566
color:
  saturation: 0.43439698149450123
  brandStrength: 0.7766260181088
  lightness: 0.4073363854549825
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  rhythmicContrast: 0.1134137671906501
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5186005434952676
analytics:
  twitter: null
  google: UA-78956265-1
  facebook: null
name: travels w// betty
cta:
  bucket: null
  version: null
  domain: null
style: the-composer
navigation:
  - name: Bookings
    url: www.bookeo.com/bettybair
    type: external
  - name: 'u p d a t e s '
    url: 'http://www.123contactform.com/form-2104949/My-Form'
    type: external
  - name: Blog
    id: 2c4f8b91-f250-4d97-b48c-ec7e58b9313b
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Betty!
description: betty!
purpose: []
