typography_spectrum: 0.24630218255333602
color:
  saturation: 0.04564984
  brandStrength: 0
  lightness: 0.5687433
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  rhythmicContrast: 0.5118152
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.849087
analytics:
  twitter: null
  google: UA-78956265-1
  facebook: null
name: travels w// betty
cta:
  bucket: null
  version: null
  domain: null
style: the-composer
navigation:
  - id: d0857391-046b-4f49-9d06-238933c505d4
    url: >-
      2016-04-22-the-snuggler-or-tim-and-eric-awesome-show-great-job-or-adul.html
    name: Videos
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: null
purpose: []
