typography_spectrum: 0.18396843178197742
color:
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
  brandStrength: 0.6301997944246978
  lightness: 0.39841181016527116
  saturation: 0.45126487757079303
  rhythmicContrast: 0.3892187913879752
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7101638002786785
analytics:
  google: null
  facebook: null
  twitter: null
name: "<span style=\"color: rgb(255, 255, 255); font-family: 'Poiret One'; font-size: 68px; letter-spacing: normal; line-height: 80px; text-align: center; background-color: rgb(0, 0, 0);\">B∃TTY⑊BAIR</span>"
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: null
purpose: []
