typography_spectrum: 0.46832620562054217
color:
  saturation: 0.9238678247202188
  brandStrength: 0.5186166507191956
  lightness: 0.7146433882880956
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  rhythmicContrast: 0.36793499207124114
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3995526854414493
analytics:
  twitter: null
  google: UA-78956265-1
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c253c39c-783b-47f9-b9a1-9ea3d95b7d07.jpg
name: travels with betty
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: i g
    url: 'https://www.instagram.com/that_betty/'
    type: external
  - name: signup
    url: 'http://www.123contactform.com/form-2104949/My-Form'
    type: external
  - name: SHOP
    url: 'http://thegrid.ai/ursa/'
    type: external
  - name: b l o g
    id: 2c4f8b91-f250-4d97-b48c-ec7e58b9313b
    type: content
  - name: gallery
    url: 'http://thegrid.ai/snuggler/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
content: []
coverPrefs:
  filter: false
description: ''
purpose:
  - type: internal
    label: blog!
    item: 2c4f8b91-f250-4d97-b48c-ec7e58b9313b
  - type: external
    url: 'http://thegrid.ai/ursa/'
    label: Shop
