layout_spectrum: 0.7449986466672271
typography_spectrum: 0.5019118096679449
color:
  saturation: 0.4365058
  brandStrength: 0.4699248
  lightness: 0.5483351
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.07647666
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-78956265-1
  facebook: null
name: travels w// betty
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: b l o g
    id: 2c4f8b91-f250-4d97-b48c-ec7e58b9313b
    type: content
  - name: i g
    url: 'https://www.instagram.com/that_betty/'
    type: external
  - name: linkedIN
    id: e705be94-fa07-4c50-ac86-e928d07edf92
    type: content
  - name: signup
    url: 'http://www.123contactform.com/form-2104949/My-Form'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
description: ''
purpose: []
